/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ToolsRaciGeneratorRouteImport } from './routes/tools/raci-generator'
import { Route as JobsSyncRouteImport } from './routes/jobs/sync'
import { Route as ApiSyncStreamRouteImport } from './routes/api/sync-stream'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ToolsRaciGeneratorImportRouteImport } from './routes/tools/raci-generator/import'

const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRaciGeneratorRoute = ToolsRaciGeneratorRouteImport.update({
  id: '/tools/raci-generator',
  path: '/tools/raci-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSyncRoute = JobsSyncRouteImport.update({
  id: '/jobs/sync',
  path: '/jobs/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncStreamRoute = ApiSyncStreamRouteImport.update({
  id: '/api/sync-stream',
  path: '/api/sync-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRaciGeneratorImportRoute =
  ToolsRaciGeneratorImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => ToolsRaciGeneratorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/typography': typeof TypographyRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/sync-stream': typeof ApiSyncStreamRoute
  '/jobs/sync': typeof JobsSyncRoute
  '/tools/raci-generator': typeof ToolsRaciGeneratorRouteWithChildren
  '/jobs': typeof JobsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/raci-generator/import': typeof ToolsRaciGeneratorImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/typography': typeof TypographyRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/sync-stream': typeof ApiSyncStreamRoute
  '/jobs/sync': typeof JobsSyncRoute
  '/tools/raci-generator': typeof ToolsRaciGeneratorRouteWithChildren
  '/jobs': typeof JobsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/raci-generator/import': typeof ToolsRaciGeneratorImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/typography': typeof TypographyRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/sync-stream': typeof ApiSyncStreamRoute
  '/jobs/sync': typeof JobsSyncRoute
  '/tools/raci-generator': typeof ToolsRaciGeneratorRouteWithChildren
  '/jobs/': typeof JobsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/raci-generator/import': typeof ToolsRaciGeneratorImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/typography'
    | '/api/categories'
    | '/api/jobs'
    | '/api/sync'
    | '/api/sync-stream'
    | '/jobs/sync'
    | '/tools/raci-generator'
    | '/jobs'
    | '/tools'
    | '/tools/raci-generator/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/typography'
    | '/api/categories'
    | '/api/jobs'
    | '/api/sync'
    | '/api/sync-stream'
    | '/jobs/sync'
    | '/tools/raci-generator'
    | '/jobs'
    | '/tools'
    | '/tools/raci-generator/import'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/typography'
    | '/api/categories'
    | '/api/jobs'
    | '/api/sync'
    | '/api/sync-stream'
    | '/jobs/sync'
    | '/tools/raci-generator'
    | '/jobs/'
    | '/tools/'
    | '/tools/raci-generator/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  TypographyRoute: typeof TypographyRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiSyncStreamRoute: typeof ApiSyncStreamRoute
  JobsSyncRoute: typeof JobsSyncRoute
  ToolsRaciGeneratorRoute: typeof ToolsRaciGeneratorRouteWithChildren
  JobsIndexRoute: typeof JobsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/raci-generator': {
      id: '/tools/raci-generator'
      path: '/tools/raci-generator'
      fullPath: '/tools/raci-generator'
      preLoaderRoute: typeof ToolsRaciGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/sync': {
      id: '/jobs/sync'
      path: '/jobs/sync'
      fullPath: '/jobs/sync'
      preLoaderRoute: typeof JobsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-stream': {
      id: '/api/sync-stream'
      path: '/api/sync-stream'
      fullPath: '/api/sync-stream'
      preLoaderRoute: typeof ApiSyncStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/raci-generator/import': {
      id: '/tools/raci-generator/import'
      path: '/import'
      fullPath: '/tools/raci-generator/import'
      preLoaderRoute: typeof ToolsRaciGeneratorImportRouteImport
      parentRoute: typeof ToolsRaciGeneratorRoute
    }
  }
}

interface ToolsRaciGeneratorRouteChildren {
  ToolsRaciGeneratorImportRoute: typeof ToolsRaciGeneratorImportRoute
}

const ToolsRaciGeneratorRouteChildren: ToolsRaciGeneratorRouteChildren = {
  ToolsRaciGeneratorImportRoute: ToolsRaciGeneratorImportRoute,
}

const ToolsRaciGeneratorRouteWithChildren =
  ToolsRaciGeneratorRoute._addFileChildren(ToolsRaciGeneratorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  TypographyRoute: TypographyRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiSyncStreamRoute: ApiSyncStreamRoute,
  JobsSyncRoute: JobsSyncRoute,
  ToolsRaciGeneratorRoute: ToolsRaciGeneratorRouteWithChildren,
  JobsIndexRoute: JobsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
