/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestSimpleInsertRouteImport } from './routes/api/test-simple-insert'
import { Route as ApiTestJobsRouteImport } from './routes/api/test-jobs'
import { Route as ApiTestInsertRouteImport } from './routes/api/test-insert'
import { Route as ApiTestEncodingRouteImport } from './routes/api/test-encoding'
import { Route as ApiTestDbRouteImport } from './routes/api/test-db'
import { Route as ApiSyncStreamRouteImport } from './routes/api/sync-stream'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiDebugDbRouteImport } from './routes/api/debug-db'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiV2SyncRouteImport } from './routes/api/v2/sync'
import { Route as ApiV2SearchCompaniesRouteImport } from './routes/api/v2/search-companies'
import { Route as ApiV2PruneRouteImport } from './routes/api/v2/prune'
import { Route as ApiV2DeduplicateRouteImport } from './routes/api/v2/deduplicate'
import { Route as ApiV2SyncStatusSyncIdRouteImport } from './routes/api/v2/sync-status.$syncId'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSimpleInsertRoute = ApiTestSimpleInsertRouteImport.update({
  id: '/api/test-simple-insert',
  path: '/api/test-simple-insert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestJobsRoute = ApiTestJobsRouteImport.update({
  id: '/api/test-jobs',
  path: '/api/test-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestInsertRoute = ApiTestInsertRouteImport.update({
  id: '/api/test-insert',
  path: '/api/test-insert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestEncodingRoute = ApiTestEncodingRouteImport.update({
  id: '/api/test-encoding',
  path: '/api/test-encoding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestDbRoute = ApiTestDbRouteImport.update({
  id: '/api/test-db',
  path: '/api/test-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncStreamRoute = ApiSyncStreamRouteImport.update({
  id: '/api/sync-stream',
  path: '/api/sync-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugDbRoute = ApiDebugDbRouteImport.update({
  id: '/api/debug-db',
  path: '/api/debug-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2SyncRoute = ApiV2SyncRouteImport.update({
  id: '/api/v2/sync',
  path: '/api/v2/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2SearchCompaniesRoute = ApiV2SearchCompaniesRouteImport.update({
  id: '/api/v2/search-companies',
  path: '/api/v2/search-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2PruneRoute = ApiV2PruneRouteImport.update({
  id: '/api/v2/prune',
  path: '/api/v2/prune',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2DeduplicateRoute = ApiV2DeduplicateRouteImport.update({
  id: '/api/v2/deduplicate',
  path: '/api/v2/deduplicate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2SyncStatusSyncIdRoute = ApiV2SyncStatusSyncIdRouteImport.update({
  id: '/api/v2/sync-status/$syncId',
  path: '/api/v2/sync-status/$syncId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sync': typeof SyncRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/debug-db': typeof ApiDebugDbRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/sync-stream': typeof ApiSyncStreamRoute
  '/api/test-db': typeof ApiTestDbRoute
  '/api/test-encoding': typeof ApiTestEncodingRoute
  '/api/test-insert': typeof ApiTestInsertRoute
  '/api/test-jobs': typeof ApiTestJobsRoute
  '/api/test-simple-insert': typeof ApiTestSimpleInsertRoute
  '/api/v2/deduplicate': typeof ApiV2DeduplicateRoute
  '/api/v2/prune': typeof ApiV2PruneRoute
  '/api/v2/search-companies': typeof ApiV2SearchCompaniesRoute
  '/api/v2/sync': typeof ApiV2SyncRoute
  '/api/v2/sync-status/$syncId': typeof ApiV2SyncStatusSyncIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sync': typeof SyncRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/debug-db': typeof ApiDebugDbRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/sync-stream': typeof ApiSyncStreamRoute
  '/api/test-db': typeof ApiTestDbRoute
  '/api/test-encoding': typeof ApiTestEncodingRoute
  '/api/test-insert': typeof ApiTestInsertRoute
  '/api/test-jobs': typeof ApiTestJobsRoute
  '/api/test-simple-insert': typeof ApiTestSimpleInsertRoute
  '/api/v2/deduplicate': typeof ApiV2DeduplicateRoute
  '/api/v2/prune': typeof ApiV2PruneRoute
  '/api/v2/search-companies': typeof ApiV2SearchCompaniesRoute
  '/api/v2/sync': typeof ApiV2SyncRoute
  '/api/v2/sync-status/$syncId': typeof ApiV2SyncStatusSyncIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sync': typeof SyncRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/debug-db': typeof ApiDebugDbRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/sync-stream': typeof ApiSyncStreamRoute
  '/api/test-db': typeof ApiTestDbRoute
  '/api/test-encoding': typeof ApiTestEncodingRoute
  '/api/test-insert': typeof ApiTestInsertRoute
  '/api/test-jobs': typeof ApiTestJobsRoute
  '/api/test-simple-insert': typeof ApiTestSimpleInsertRoute
  '/api/v2/deduplicate': typeof ApiV2DeduplicateRoute
  '/api/v2/prune': typeof ApiV2PruneRoute
  '/api/v2/search-companies': typeof ApiV2SearchCompaniesRoute
  '/api/v2/sync': typeof ApiV2SyncRoute
  '/api/v2/sync-status/$syncId': typeof ApiV2SyncStatusSyncIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sync'
    | '/api/categories'
    | '/api/debug-db'
    | '/api/jobs'
    | '/api/sync'
    | '/api/sync-stream'
    | '/api/test-db'
    | '/api/test-encoding'
    | '/api/test-insert'
    | '/api/test-jobs'
    | '/api/test-simple-insert'
    | '/api/v2/deduplicate'
    | '/api/v2/prune'
    | '/api/v2/search-companies'
    | '/api/v2/sync'
    | '/api/v2/sync-status/$syncId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sync'
    | '/api/categories'
    | '/api/debug-db'
    | '/api/jobs'
    | '/api/sync'
    | '/api/sync-stream'
    | '/api/test-db'
    | '/api/test-encoding'
    | '/api/test-insert'
    | '/api/test-jobs'
    | '/api/test-simple-insert'
    | '/api/v2/deduplicate'
    | '/api/v2/prune'
    | '/api/v2/search-companies'
    | '/api/v2/sync'
    | '/api/v2/sync-status/$syncId'
  id:
    | '__root__'
    | '/'
    | '/sync'
    | '/api/categories'
    | '/api/debug-db'
    | '/api/jobs'
    | '/api/sync'
    | '/api/sync-stream'
    | '/api/test-db'
    | '/api/test-encoding'
    | '/api/test-insert'
    | '/api/test-jobs'
    | '/api/test-simple-insert'
    | '/api/v2/deduplicate'
    | '/api/v2/prune'
    | '/api/v2/search-companies'
    | '/api/v2/sync'
    | '/api/v2/sync-status/$syncId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SyncRoute: typeof SyncRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiDebugDbRoute: typeof ApiDebugDbRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiSyncStreamRoute: typeof ApiSyncStreamRoute
  ApiTestDbRoute: typeof ApiTestDbRoute
  ApiTestEncodingRoute: typeof ApiTestEncodingRoute
  ApiTestInsertRoute: typeof ApiTestInsertRoute
  ApiTestJobsRoute: typeof ApiTestJobsRoute
  ApiTestSimpleInsertRoute: typeof ApiTestSimpleInsertRoute
  ApiV2DeduplicateRoute: typeof ApiV2DeduplicateRoute
  ApiV2PruneRoute: typeof ApiV2PruneRoute
  ApiV2SearchCompaniesRoute: typeof ApiV2SearchCompaniesRoute
  ApiV2SyncRoute: typeof ApiV2SyncRoute
  ApiV2SyncStatusSyncIdRoute: typeof ApiV2SyncStatusSyncIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-simple-insert': {
      id: '/api/test-simple-insert'
      path: '/api/test-simple-insert'
      fullPath: '/api/test-simple-insert'
      preLoaderRoute: typeof ApiTestSimpleInsertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-jobs': {
      id: '/api/test-jobs'
      path: '/api/test-jobs'
      fullPath: '/api/test-jobs'
      preLoaderRoute: typeof ApiTestJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-insert': {
      id: '/api/test-insert'
      path: '/api/test-insert'
      fullPath: '/api/test-insert'
      preLoaderRoute: typeof ApiTestInsertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-encoding': {
      id: '/api/test-encoding'
      path: '/api/test-encoding'
      fullPath: '/api/test-encoding'
      preLoaderRoute: typeof ApiTestEncodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-db': {
      id: '/api/test-db'
      path: '/api/test-db'
      fullPath: '/api/test-db'
      preLoaderRoute: typeof ApiTestDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-stream': {
      id: '/api/sync-stream'
      path: '/api/sync-stream'
      fullPath: '/api/sync-stream'
      preLoaderRoute: typeof ApiSyncStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-db': {
      id: '/api/debug-db'
      path: '/api/debug-db'
      fullPath: '/api/debug-db'
      preLoaderRoute: typeof ApiDebugDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/sync': {
      id: '/api/v2/sync'
      path: '/api/v2/sync'
      fullPath: '/api/v2/sync'
      preLoaderRoute: typeof ApiV2SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/search-companies': {
      id: '/api/v2/search-companies'
      path: '/api/v2/search-companies'
      fullPath: '/api/v2/search-companies'
      preLoaderRoute: typeof ApiV2SearchCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/prune': {
      id: '/api/v2/prune'
      path: '/api/v2/prune'
      fullPath: '/api/v2/prune'
      preLoaderRoute: typeof ApiV2PruneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/deduplicate': {
      id: '/api/v2/deduplicate'
      path: '/api/v2/deduplicate'
      fullPath: '/api/v2/deduplicate'
      preLoaderRoute: typeof ApiV2DeduplicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/sync-status/$syncId': {
      id: '/api/v2/sync-status/$syncId'
      path: '/api/v2/sync-status/$syncId'
      fullPath: '/api/v2/sync-status/$syncId'
      preLoaderRoute: typeof ApiV2SyncStatusSyncIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SyncRoute: SyncRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiDebugDbRoute: ApiDebugDbRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiSyncStreamRoute: ApiSyncStreamRoute,
  ApiTestDbRoute: ApiTestDbRoute,
  ApiTestEncodingRoute: ApiTestEncodingRoute,
  ApiTestInsertRoute: ApiTestInsertRoute,
  ApiTestJobsRoute: ApiTestJobsRoute,
  ApiTestSimpleInsertRoute: ApiTestSimpleInsertRoute,
  ApiV2DeduplicateRoute: ApiV2DeduplicateRoute,
  ApiV2PruneRoute: ApiV2PruneRoute,
  ApiV2SearchCompaniesRoute: ApiV2SearchCompaniesRoute,
  ApiV2SyncRoute: ApiV2SyncRoute,
  ApiV2SyncStatusSyncIdRoute: ApiV2SyncStatusSyncIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
