name = "spearyx-corporate"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]
main = "dist/server/server.js"

[[kv_namespaces]]
binding = "KV"
id = "07de8044b8154750a0cfc2e5eaa60f2c"

[[d1_databases]]
binding = "DB"
database_name = "spearyx-jobs"
database_id = "991bbe3f-8b3a-4ce4-9de8-c2110052662f"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[assets]
directory = "dist/client"
