/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsRaciGeneratorRouteImport } from './routes/tools/raci-generator'

const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRaciGeneratorRoute = ToolsRaciGeneratorRouteImport.update({
  id: '/tools/raci-generator',
  path: '/tools/raci-generator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/typography': typeof TypographyRoute
  '/tools/raci-generator': typeof ToolsRaciGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/typography': typeof TypographyRoute
  '/tools/raci-generator': typeof ToolsRaciGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/typography': typeof TypographyRoute
  '/tools/raci-generator': typeof ToolsRaciGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cards' | '/typography' | '/tools/raci-generator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cards' | '/typography' | '/tools/raci-generator'
  id: '__root__' | '/' | '/cards' | '/typography' | '/tools/raci-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  TypographyRoute: typeof TypographyRoute
  ToolsRaciGeneratorRoute: typeof ToolsRaciGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/raci-generator': {
      id: '/tools/raci-generator'
      path: '/tools/raci-generator'
      fullPath: '/tools/raci-generator'
      preLoaderRoute: typeof ToolsRaciGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  TypographyRoute: TypographyRoute,
  ToolsRaciGeneratorRoute: ToolsRaciGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
