name = "spearyx-tools"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]
main = "worker.ts"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[assets]
directory = "dist/client"

[ai]
binding = "AI"
remote = true

[[routes]]
pattern = "tools.spearyx.com"
custom_domain = true
