/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaciGeneratorRouteImport } from './routes/raci-generator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RaciGeneratorImportRouteImport } from './routes/raci-generator/import'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'

const RaciGeneratorRoute = RaciGeneratorRouteImport.update({
  id: '/raci-generator',
  path: '/raci-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaciGeneratorImportRoute = RaciGeneratorImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => RaciGeneratorRoute,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/raci-generator': typeof RaciGeneratorRouteWithChildren
  '/raci-generator/import': typeof RaciGeneratorImportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/raci-generator': typeof RaciGeneratorRouteWithChildren
  '/raci-generator/import': typeof RaciGeneratorImportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/raci-generator': typeof RaciGeneratorRouteWithChildren
  '/raci-generator/import': typeof RaciGeneratorImportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/raci-generator'
    | '/raci-generator/import'
    | '/api/ai/generate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/raci-generator' | '/raci-generator/import' | '/api/ai/generate'
  id:
    | '__root__'
    | '/'
    | '/raci-generator'
    | '/raci-generator/import'
    | '/api/ai/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RaciGeneratorRoute: typeof RaciGeneratorRouteWithChildren
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raci-generator': {
      id: '/raci-generator'
      path: '/raci-generator'
      fullPath: '/raci-generator'
      preLoaderRoute: typeof RaciGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raci-generator/import': {
      id: '/raci-generator/import'
      path: '/import'
      fullPath: '/raci-generator/import'
      preLoaderRoute: typeof RaciGeneratorImportRouteImport
      parentRoute: typeof RaciGeneratorRoute
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RaciGeneratorRouteChildren {
  RaciGeneratorImportRoute: typeof RaciGeneratorImportRoute
}

const RaciGeneratorRouteChildren: RaciGeneratorRouteChildren = {
  RaciGeneratorImportRoute: RaciGeneratorImportRoute,
}

const RaciGeneratorRouteWithChildren = RaciGeneratorRoute._addFileChildren(
  RaciGeneratorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RaciGeneratorRoute: RaciGeneratorRouteWithChildren,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
